services:
  portfolio-dev:
    container_name: portfolio_dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 5173:5173 # React App
      # - 6006:6006 # Storybook
    develop:
      watch:
        - action: sync
          path: .
          target: /app
